FROM python:3.8-slim
RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y git 
RUN mkdir dashapp 
WORKDIR dashapp
RUN git clone https://github.com/ipa-rar/THMHO_dashboard.git
WORKDIR dashapp/THMHO_dashboard/src/dash
RUN pip install wheel 
RUN pip install pymongo dash numpy pandas dash-bootstrap-components
CMD ["python3", "app.py"]

