name: Sync to Upstream

on:
  schedule:
    - cron:  '0 8 * * 1,4'
    # scheduled at 08:00 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ipa-rar
          base: master
          head: master
